### ISSUE TITLE
Frontend - Improvement - Vertical Admin Form

### ISSUE THREAD

**Issue by lahann** [lahann/RMIT-WebProgramming-React#6]
You can change the layout of form to make it vertical so it looks better.
- First the vertical form
- Then the table with the products/ categories

**Comment by linhthikhanhdo** [comment]
I'll make the forms to add new product/ product type vertical. Will leave the tables horizontal as how would you make them vertical :-)

**Comment by linhthikhanhdo** [comment]
no need to update productType form since not as messy as product
